// <auto-generated />
using System;
using HRPersonnelSystem.DAL.Concrete.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRPersonnelSystem.DAL.Migrations
{
    [DbContext(typeof(PersonnelSystemDbContext))]
    [Migration("20231018134303_fr")]
    partial class fr
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HRPersonnelSystem.Entities.AdvancePayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdvancePaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrencyUnit")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfReply")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Explain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AdvancePayment");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f8bd10ce-80d7-4211-9893-a943cb333338"),
                            AdvancePaymentType = "Bireysel",
                            Amount = 5000m,
                            ApprovalStatus = 2,
                            CreatedDate = new DateTime(2023, 10, 18, 16, 43, 2, 232, DateTimeKind.Local).AddTicks(6798),
                            CurrencyUnit = 2,
                            EmployeeId = new Guid("7db5918a-64b7-4d74-8d16-bb52fa969631"),
                            Explain = "",
                            IsDeleted = false,
                            RequestDate = new DateTime(2023, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HRPersonnelSystem.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cba7d3c3-51e2-4694-9003-4177b2c43808"),
                            ConcurrencyStamp = "7aab2df0-9fa9-404c-8dd3-7ccf4f745298",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        },
                        new
                        {
                            Id = new Guid("b452c8e5-2d3c-4806-94b1-ad8e464ddbfe"),
                            ConcurrencyStamp = "953ab15f-0739-430f-b922-71d47965a256",
                            Name = "CompanyDirector",
                            NormalizedName = "COMPANYDIRECTOR"
                        },
                        new
                        {
                            Id = new Guid("2a56646d-1ce3-452c-9aee-f64cef46892a"),
                            ConcurrencyStamp = "78251fcb-3a01-4e55-b0aa-1f6652dab181",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("HRPersonnelSystem.Entities.AppRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("HRPersonnelSystem.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("AppUser");
                });

            modelBuilder.Entity("HRPersonnelSystem.Entities.AppUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("HRPersonnelSystem.Entities.AppUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("HRPersonnelSystem.Entities.AppUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("7db5918a-64b7-4d74-8d16-bb52fa969631"),
                            RoleId = new Guid("cba7d3c3-51e2-4694-9003-4177b2c43808")
                        },
                        new
                        {
                            UserId = new Guid("fb944ae2-e89b-4f8e-b17b-b7fe1ece2ead"),
                            RoleId = new Guid("b452c8e5-2d3c-4806-94b1-ad8e464ddbfe")
                        },
                        new
                        {
                            UserId = new Guid("d6aab0eb-0052-48bd-a830-37a8e5e67f86"),
                            RoleId = new Guid("2a56646d-1ce3-452c-9aee-f64cef46892a")
                        },
                        new
                        {
                            UserId = new Guid("b7acc710-c1b9-4ae4-9a6b-efda8160cf4f"),
                            RoleId = new Guid("cba7d3c3-51e2-4694-9003-4177b2c43808")
                        });
                });

            modelBuilder.Entity("HRPersonnelSystem.Entities.AppUserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HRPersonnelSystem.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ContractEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ContractStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MersisNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfEmployees")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxOffice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("YearOfEstablishment")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0c026bc4-e4d4-44fd-b210-02e7a6a172c9"),
                            Address = "Küçükyali merkez mh. oniki sk. No : 14 Ayazağa Plaza. Sarıyer / Istanbul",
                            CompanyName = "BilgeAdam Teknoloji",
                            CompanyTitle = "LTD.ŞTI.",
                            ContractEndDate = new DateTime(2025, 10, 18, 16, 43, 2, 241, DateTimeKind.Local).AddTicks(3036),
                            ContractStartDate = new DateTime(2023, 2, 18, 16, 43, 2, 241, DateTimeKind.Local).AddTicks(3033),
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2023, 10, 18, 16, 43, 2, 241, DateTimeKind.Local).AddTicks(3011),
                            Email = "info@bilgeadam.com",
                            ImagePath = "indir.png",
                            IsActive = true,
                            IsDeleted = false,
                            MersisNumber = "0470000911900015",
                            NumberOfEmployees = 88,
                            Phone = "0212 473 88 88",
                            TaxNumber = "4700009119",
                            TaxOffice = "Aksaray V.D",
                            YearOfEstablishment = new DateTime(1998, 10, 18, 16, 43, 2, 241, DateTimeKind.Local).AddTicks(3031)
                        });
                });

            modelBuilder.Entity("HRPersonnelSystem.Entities.Expenditure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfReply")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExpenditureType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Expenditure");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3397bff8-1261-4603-8965-9d596246e4b8"),
                            Amount = 800m,
                            ApprovalStatus = "Bekleyen",
                            CreatedDate = new DateTime(2023, 10, 18, 16, 43, 2, 232, DateTimeKind.Local).AddTicks(7822),
                            CurrencyUnit = "TL",
                            EmployeeId = new Guid("7db5918a-64b7-4d74-8d16-bb52fa969631"),
                            ExpenditureType = "Seyahat",
                            IsDeleted = false,
                            RequestDate = new DateTime(2023, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2ffbe4d4-c782-4a19-bd89-0a8624bed3ee"),
                            Amount = 500m,
                            ApprovalStatus = "Reddedildi",
                            CreatedDate = new DateTime(2023, 10, 18, 16, 43, 2, 232, DateTimeKind.Local).AddTicks(7883),
                            CurrencyUnit = "TL",
                            EmployeeId = new Guid("7db5918a-64b7-4d74-8d16-bb52fa969631"),
                            ExpenditureType = "Konaklama",
                            IsDeleted = false,
                            RequestDate = new DateTime(2023, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HRPersonnelSystem.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountOfDay")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfReply")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PermissionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Permission");

                    b.HasData(
                        new
                        {
                            Id = new Guid("305ef3c8-fc05-46b2-b054-c49ad270be26"),
                            ApprovalStatus = "Bekleyen",
                            CountOfDay = 21,
                            CreatedDate = new DateTime(2023, 10, 18, 16, 43, 2, 241, DateTimeKind.Local).AddTicks(5881),
                            EmployeeId = new Guid("7db5918a-64b7-4d74-8d16-bb52fa969631"),
                            Gender = 1,
                            IsActive = true,
                            IsDeleted = false,
                            PermissionType = "Askerlik",
                            RequestDate = new DateTime(2023, 10, 18, 16, 43, 2, 241, DateTimeKind.Local).AddTicks(5891),
                            StartDate = new DateTime(2023, 11, 7, 16, 43, 2, 241, DateTimeKind.Local).AddTicks(5888)
                        },
                        new
                        {
                            Id = new Guid("230ae8d2-be96-40bf-8639-566de6ba3a73"),
                            ApprovalStatus = "Bekleyen",
                            CountOfDay = 5,
                            CreatedDate = new DateTime(2023, 10, 18, 16, 43, 2, 241, DateTimeKind.Local).AddTicks(5909),
                            EmployeeId = new Guid("7db5918a-64b7-4d74-8d16-bb52fa969631"),
                            Gender = 1,
                            IsActive = true,
                            IsDeleted = false,
                            PermissionType = "Babalık",
                            RequestDate = new DateTime(2024, 1, 16, 16, 43, 2, 241, DateTimeKind.Local).AddTicks(5913),
                            StartDate = new DateTime(2024, 1, 26, 16, 43, 2, 241, DateTimeKind.Local).AddTicks(5912)
                        },
                        new
                        {
                            Id = new Guid("7fe8e741-7e57-41ea-ae05-1697b1c18f77"),
                            ApprovalStatus = "Onaylandı",
                            CountOfDay = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 16, 43, 2, 241, DateTimeKind.Local).AddTicks(5919),
                            EmployeeId = new Guid("7db5918a-64b7-4d74-8d16-bb52fa969631"),
                            Gender = 1,
                            IsActive = true,
                            IsDeleted = false,
                            PermissionType = "Hastalık",
                            RequestDate = new DateTime(2023, 10, 18, 16, 43, 2, 241, DateTimeKind.Local).AddTicks(5922),
                            StartDate = new DateTime(2023, 10, 18, 16, 43, 2, 241, DateTimeKind.Local).AddTicks(5921)
                        },
                        new
                        {
                            Id = new Guid("702dabb3-d6d4-4ec0-a6f1-ae329c81b649"),
                            ApprovalStatus = "Onaylandı",
                            CountOfDay = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 16, 43, 2, 241, DateTimeKind.Local).AddTicks(5927),
                            EmployeeId = new Guid("7db5918a-64b7-4d74-8d16-bb52fa969631"),
                            Gender = 1,
                            IsActive = true,
                            IsDeleted = false,
                            PermissionType = "Evlilik",
                            RequestDate = new DateTime(2024, 8, 13, 16, 43, 2, 241, DateTimeKind.Local).AddTicks(5932),
                            StartDate = new DateTime(2024, 9, 7, 16, 43, 2, 241, DateTimeKind.Local).AddTicks(5931)
                        },
                        new
                        {
                            Id = new Guid("38b5f216-c008-4e81-9cac-337f8ad7e283"),
                            ApprovalStatus = "Reddedildi",
                            CountOfDay = 5,
                            CreatedDate = new DateTime(2023, 10, 18, 16, 43, 2, 241, DateTimeKind.Local).AddTicks(5937),
                            EmployeeId = new Guid("7db5918a-64b7-4d74-8d16-bb52fa969631"),
                            Gender = 1,
                            IsActive = true,
                            IsDeleted = false,
                            PermissionType = "Yıllık",
                            RequestDate = new DateTime(2024, 7, 14, 16, 43, 2, 241, DateTimeKind.Local).AddTicks(5941),
                            StartDate = new DateTime(2024, 7, 19, 16, 43, 2, 241, DateTimeKind.Local).AddTicks(5939)
                        },
                        new
                        {
                            Id = new Guid("736b4a73-d1e5-4c87-80b7-8584824b4e57"),
                            ApprovalStatus = "Reddedildi",
                            CountOfDay = 10,
                            CreatedDate = new DateTime(2023, 10, 18, 16, 43, 2, 241, DateTimeKind.Local).AddTicks(5946),
                            EmployeeId = new Guid("7db5918a-64b7-4d74-8d16-bb52fa969631"),
                            Gender = 1,
                            IsActive = true,
                            IsDeleted = false,
                            PermissionType = "Refakat",
                            RequestDate = new DateTime(2024, 5, 3, 16, 43, 2, 241, DateTimeKind.Local).AddTicks(5949),
                            StartDate = new DateTime(2024, 5, 5, 16, 43, 2, 241, DateTimeKind.Local).AddTicks(5948)
                        });
                });

            modelBuilder.Entity("HRPersonnelSystem.Entities.Admin", b =>
                {
                    b.HasBaseType("HRPersonnelSystem.Entities.AppUser");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfHire")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfTermination")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<string>("SecondLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Admin");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6aab0eb-0052-48bd-a830-37a8e5e67f86"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dc8b64d5-3b50-4cf0-8ab9-161e34dba91d",
                            Email = "erden.timur@bilgeadam.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ERDEN.TIMUR@BILGEADAM.COM",
                            NormalizedUserName = "ERDEN.TIMUR@BILGEADAM.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEDn6OIY52YoN+mUTpt13jXqACQRRnHqeTS7xHBoSxv56wMqZM0ZhYLzXqh/4Hss44A==",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "1",
                            TwoFactorEnabled = false,
                            UserName = "erden.timur@bilgeadam.com",
                            Address = "Okul yolu sok. Zincertepe Apt. Bostancı / İstanbul",
                            BirthDate = new DateTime(1985, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Dolmabahçe",
                            CompanyName = "BilgeAdam",
                            DateOfHire = new DateTime(2023, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Software",
                            FirstName = "Erden",
                            Gender = 1,
                            ImagePath = "ErdenTimur.jpeg",
                            IsActive = true,
                            Job = "Admin",
                            LastName = "Timur",
                            Salary = 45000.0,
                            TCNumber = "12345678900"
                        });
                });

            modelBuilder.Entity("HRPersonnelSystem.Entities.CompanyDirector", b =>
                {
                    b.HasBaseType("HRPersonnelSystem.Entities.AppUser");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompanyDirector_Address");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CompanyDirector_BirthDate");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompanyDirector_BirthPlace");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfHire")
                        .HasColumnType("datetime2")
                        .HasColumnName("CompanyDirector_DateOfHire");

                    b.Property<DateTime?>("DateOfTermination")
                        .HasColumnType("datetime2")
                        .HasColumnName("CompanyDirector_DateOfTermination");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompanyDirector_Department");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompanyDirector_FirstName");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("CompanyDirector_Gender");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompanyDirector_ImagePath");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("CompanyDirector_IsActive");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompanyDirector_Job");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompanyDirector_LastName");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompanyDirector_MiddleName");

                    b.Property<double>("Salary")
                        .HasColumnType("float")
                        .HasColumnName("CompanyDirector_Salary");

                    b.Property<string>("SecondLastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompanyDirector_SecondLastName");

                    b.Property<string>("TCNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompanyDirector_TCNumber");

                    b.HasIndex("CompanyId");

                    b.HasDiscriminator().HasValue("CompanyDirector");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fb944ae2-e89b-4f8e-b17b-b7fe1ece2ead"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b83c2747-f59b-4811-917a-178d174fa5f8",
                            Email = "gizem.altin@bilgeadamboost.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "GIZEM.ALTIN@BILGEADAMBOOST.COM",
                            NormalizedUserName = "GIZEM.ALTIN@BILGEADAMBOOST.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAECjwxUYo3zZk5xkLB+IzmtdaCwjl+Rf7rr28qFFssowRY+hSl1AhFO+OJOpFBHUr0w==",
                            PhoneNumber = "0522222222",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "1",
                            TwoFactorEnabled = false,
                            UserName = "gizem.altin@bilgeadamboost.com",
                            Address = "Süründere Mah. Orkun Sok. No:55 Kızılay/Ankara",
                            BirthDate = new DateTime(1991, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Ankara",
                            CompanyId = new Guid("0c026bc4-e4d4-44fd-b210-02e7a6a172c9"),
                            DateOfHire = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Bilişim Teknojileri",
                            FirstName = "Gizem",
                            Gender = 0,
                            ImagePath = "Gamze.jpg",
                            IsActive = true,
                            Job = "Ekip Lideri",
                            LastName = "Altın",
                            Salary = 47000.0,
                            TCNumber = "12345678911"
                        });
                });

            modelBuilder.Entity("HRPersonnelSystem.Entities.Employee", b =>
                {
                    b.HasBaseType("HRPersonnelSystem.Entities.AppUser");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Employee_Address");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Employee_BirthDate");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Employee_BirthPlace");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Employee_CompanyId");

                    b.Property<DateTime>("DateOfHire")
                        .HasColumnType("datetime2")
                        .HasColumnName("Employee_DateOfHire");

                    b.Property<DateTime?>("DateOfTermination")
                        .HasColumnType("datetime2")
                        .HasColumnName("Employee_DateOfTermination");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Employee_Department");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Employee_FirstName");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("Employee_Gender");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Employee_ImagePath");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Employee_IsActive");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Employee_Job");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Employee_LastName");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Employee_MiddleName");

                    b.Property<double>("Salary")
                        .HasColumnType("float")
                        .HasColumnName("Employee_Salary");

                    b.Property<string>("SecondLastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Employee_SecondLastName");

                    b.Property<string>("TCNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Employee_TCNumber");

                    b.HasIndex("CompanyId");

                    b.HasDiscriminator().HasValue("Employee");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7db5918a-64b7-4d74-8d16-bb52fa969631"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8fbe172f-f005-4688-b29b-c1f423696851",
                            Email = "burak.pekmez@bilgeadamboost.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BURAK.PEKMEZ@BILGEADAMBOOST.COM",
                            NormalizedUserName = "BURAK.PEKMEZ@BILGEADAMBOOST.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEDeR4uXwJ1Xdg5upZntp1MG7egardw5b1m5bsLdcp+6GL+iYe3CfmP02sdXWHQinIA==",
                            PhoneNumber = "055555555",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "1",
                            TwoFactorEnabled = false,
                            UserName = "burak.pekmez@bilgeadamboost.com",
                            Address = " BilgeAdam Kadıköy. Adres. Caferağa Mah. Mühürdar Cad. No:76 Kadıköy / İSTANBUL​",
                            BirthDate = new DateTime(1998, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Bakırköy",
                            CompanyId = new Guid("0c026bc4-e4d4-44fd-b210-02e7a6a172c9"),
                            DateOfHire = new DateTime(2023, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Software",
                            FirstName = "Burak",
                            Gender = 1,
                            ImagePath = "Burak.jpg",
                            IsActive = true,
                            Job = "Developer",
                            LastName = "Pekmez",
                            Salary = 23000.0,
                            TCNumber = "12345678910"
                        },
                        new
                        {
                            Id = new Guid("b7acc710-c1b9-4ae4-9a6b-efda8160cf4f"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a614f822-f19d-42e3-beef-0bfef414c67e",
                            Email = "hande.pekmez@bilgeadamboost.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "HANDE.PEKMEZ@BILGEADAMBOOST.COM",
                            NormalizedUserName = "HANDE.PEKMEZ@BILGEADAMBOOST.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEO5HxusDSaTVmHFDRXTukrhgmQYvMBpiqd7QymHCWreNWpJ+hiQZm2wNo4xoDXjwIg==",
                            PhoneNumber = "05001905222",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "1",
                            TwoFactorEnabled = false,
                            UserName = "hande.pekmez@bilgeadamboost.com",
                            Address = " BilgeAdam Kadıköy. Adres. Caferağa Mah. Mühürdar Cad. No:76 Kadıköy / İSTANBUL​",
                            BirthDate = new DateTime(1997, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Tuzla",
                            CompanyId = new Guid("0c026bc4-e4d4-44fd-b210-02e7a6a172c9"),
                            DateOfHire = new DateTime(2021, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Software",
                            FirstName = "Hande",
                            Gender = 0,
                            ImagePath = "Hande.jpg",
                            IsActive = true,
                            Job = "Developer",
                            LastName = "Pekmez",
                            Salary = 32000.0,
                            TCNumber = "92345678910"
                        });
                });

            modelBuilder.Entity("HRPersonnelSystem.Entities.AdvancePayment", b =>
                {
                    b.HasOne("HRPersonnelSystem.Entities.Employee", "Employee")
                        .WithMany("AdvancePayments")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRPersonnelSystem.Entities.AppRoleClaim", b =>
                {
                    b.HasOne("HRPersonnelSystem.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRPersonnelSystem.Entities.AppUserClaim", b =>
                {
                    b.HasOne("HRPersonnelSystem.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRPersonnelSystem.Entities.AppUserLogin", b =>
                {
                    b.HasOne("HRPersonnelSystem.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRPersonnelSystem.Entities.AppUserRole", b =>
                {
                    b.HasOne("HRPersonnelSystem.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRPersonnelSystem.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRPersonnelSystem.Entities.AppUserToken", b =>
                {
                    b.HasOne("HRPersonnelSystem.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRPersonnelSystem.Entities.Expenditure", b =>
                {
                    b.HasOne("HRPersonnelSystem.Entities.Employee", "Employee")
                        .WithMany("Expenditures")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRPersonnelSystem.Entities.Permission", b =>
                {
                    b.HasOne("HRPersonnelSystem.Entities.Employee", "Employee")
                        .WithMany("Permissions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRPersonnelSystem.Entities.CompanyDirector", b =>
                {
                    b.HasOne("HRPersonnelSystem.Entities.Company", "Company")
                        .WithMany("CompanyDirectors")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HRPersonnelSystem.Entities.Employee", b =>
                {
                    b.HasOne("HRPersonnelSystem.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HRPersonnelSystem.Entities.Company", b =>
                {
                    b.Navigation("CompanyDirectors");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HRPersonnelSystem.Entities.Employee", b =>
                {
                    b.Navigation("AdvancePayments");

                    b.Navigation("Expenditures");

                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
